apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: svn-deployment
  name: svn-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svn-deployment
    spec:
      containers:
      - name: svn-deployment
        image: tianctrl/svn-docker:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3690