apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: svn-deployment
  name: svn-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svn-deployment
    spec:
      volumes:
      - name: svn-data
        hostPath:
          path: /home/svn
      containers:
      - name: svn-deployment
        image: tianctrl/svn-docker:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3690
        volumeMounts:
        - mountPath: /var/svn
          name: svn-data